### ISSUE TITLE
Pagina não carrega

### ISSUE THREAD

**Issue by JoaoPedro110** [Mayck-E/PET-SHOP#1]
<img width="644" alt="Captura de tela 2023-03-01 150149" src="https://user-images.githubusercontent.com/126287368/222225992-449a9a23-2024-4838-8b06-f526004a6085.png">
Boa Tarde a minha pagina não esta carregando , você poderia me ajuda

**Comment by Mayck-E** [comment]
Posso sim, daqui a pouco já vejo

**Comment by JoaoPedro110** [comment]
> Posso sim, daqui um pouco já vejo

Obrigado , mas já conseguir estar acessando o seu site
