### ISSUE TITLE
companheiro mayck 

### ISSUE THREAD

**Issue by JoaoPedro110** [Mayck-E/PET-SHOP#4]
ou como coloca as coisa do lado de cada em vezes de de baixo

**Comment by Mayck-E** [comment]
tenta usar no CSS:
box-sizing: border-box;
display: inline-block;

**Comment by JoaoPedro110** [comment]
Onde coloca? no id ou class?

**Comment by JoaoPedro110** [comment]
<img width="393" alt="Captura de tela 2023-03-22 092313" src="https://user-images.githubusercontent.com/126287368/226903542-cc83c149-18b8-4bf9-90d5-6a68491b05e2.png">
queria colocar o facebook e instagram na mesma linha

**Comment by Mayck-E** [comment]
pode por nas imagens

**Comment by Mayck-E** [comment]
tipo uma tag em comum, ou sla põe 
img {
}

**Comment by JoaoPedro110** [comment]
ok

**Comment by JoaoPedro110** [comment]
Não foi

**Comment by JoaoPedro110** [comment]
foi

**Comment by JoaoPedro110** [comment]
mas ficou uma merda
<img width="781" alt="Captura de tela 2023-03-22 093751" src="https://user-images.githubusercontent.com/126287368/226906613-1551563f-88b2-42c2-a792-93dd148859d8.png">

**Comment by JoaoPedro110** [comment]
Mayck passa o e-mail , para nois conversarmos melhor sobre o trabalho

**Comment by Mayck-E** [comment]
vi agr... quando precisar pode mandar nesse 
mayck22.03@hotmail.com

esse outro eu olho menos
eduardo.mayck22@gmail.com

**Comment by JoaoPedro110** [comment]
Boa tarde Mayck , vc sabe como colocar uma pasta dentro de outra pasta ligando com a pasta imagem?
